# Generated by Django 3.2.9 on 2021-11-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.IntegerField(choices=[(None, 'Выберите пол'), (1, 'Мужской'), (2, 'Женский'), (3, 'Неизвестно')], verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(None, 'Выберите статус'), (0, 'Неактивен'), (1, 'Активен')], verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.IntegerField(choices=[(None, 'Выберите тип'), (1, 'Первичный'), (2, 'Повторный'), (3, 'Внешний'), (4, 'Косвенный')], verbose_name='тип'),
        ),
    ]
