# Generated by Django 3.2.9 on 2021-11-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211122_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status_changed_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='дата изменения статуса'),
        ),
    ]
