# Generated by Django 3.2.9 on 2021-11-22 17:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customer_status_changed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(max_length=255, verbose_name='instagram')),
                ('telegram', models.CharField(max_length=25, verbose_name='telegram')),
                ('whatsapp', models.CharField(max_length=25, verbose_name='whatsApp')),
                ('viber', models.CharField(max_length=25, verbose_name='viber')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='e-mail'),
        ),
        migrations.CreateModel(
            name='Vkontakte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='ссылка')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.socialnetwork', verbose_name='социальная сеть')),
            ],
            options={
                'verbose_name': 'вконтакте',
                'verbose_name_plural': 'Вконтакте',
            },
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='ссылка')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.socialnetwork', verbose_name='социальная сеть')),
            ],
            options={
                'verbose_name': 'facebook',
                'verbose_name_plural': 'Facebooks',
            },
        ),
        migrations.CreateModel(
            name='AdditionalPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='дополнительный номер телефона')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'дополнительный номер',
                'verbose_name_plural': 'Дополнительные номера',
            },
        ),
        migrations.CreateModel(
            name='AdditionalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='e-mail')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'дополнительный E-mail',
                'verbose_name_plural': 'Дополнительные E-mail',
            },
        ),
    ]
