# Generated by Django 3.2.9 on 2021-11-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211122_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebook',
            options={'verbose_name': 'facebook', 'verbose_name_plural': 'Facebook'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='viber',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='viber'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='whatsApp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='сотрудник'),
        ),
    ]
