# Generated by Django 3.2.9 on 2021-11-22 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211122_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status_changed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='дата изменения статуса'),
        ),
    ]
